global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'nestjs_app'
    static_configs:
      - targets: ['host.docker.internal:3000']
      #- targets: ['gateway:3000', 'auth-service:3003', 'chat-service:3004']